sudo: required

language: python

env:
  global:
  - secure: NOxZyXwvHbX4e0yRo/u3K6/crYMA4y+4vh5lOqqdbQhYeTWrzX9QLRY11jkVCthtpORbAG+FjATmenGfxvp/Uc+OXcRyeMrRGouhKM7HU0bH3Q+xWwX3moPEXpd6QDH/Fw2EgwgCcofHvk2TBPBPdtt2rpK3iZKzZiuHbE3hS1qOc/Qlcr5xPCrwjG5s2aFDKcK8oVZ/KgSiYzLW/amMowHh7iQW+nasWal8gfGaJyo7QgXHvAGqFXEvEdgArf1HhBZqajtsK74qCwmMgRGIlPdQcGkwdroRJMIHm4Nl4Yw7H0CrMGOhdzx5h8EcHF0/DiwZQ1S0oNTOY+yRbDmpZ0miJpuTj+/jpXIeHGnvZ/5T4xvvBhy/MIYL0Db012HX//pPEdYZPHgrYiDHbXM/OoTm0JLipNqm82dmsGeRLQKtWTYLLlx8iThP+6SFsni0DXOpLQwHCfQvzCJ1wlMOvgccrMRmMnYMuCudIvu17LShZR8wriz56n585VNwlRnxdQmWmDKgq1+q9wn/TJl7Vsdnt0ZSLAew0Ip0g0z9M6gJ6ZmCCTk3z892fX7hcI78cU9yx+uP5jVos9Z7SwyF3cOr6om+57rUF99ydsJy36gC1+AQEFcSpFsSNlmU7ItKHjNKpIgOK3YeN24OQY018/QsXyHgTIW+B4+wyZa79/k=
  - secure: BdobCYhXV7mx7X3oQEdAorxpegHPgFK+/CExvPRfWsHWCOmx0N8WiQJ0qCXe7HzFQO89AdVGFYU2reHAjqkZrmLE26cQPs+l48rdsCR+WRutLsRSjBfNdlM8wteFZ8O+Y2kPeD8kS1SvA9sOldVwbHFwf1bf/qg/KXbGeuoxRBgm3UbZZHZurKVXJug/3yyyRRagIispXr7O8CTr08wYzStW3iZlBxwcuPimzhWzMqxqPMQX/0hV0NM63VbZ3iQRaQgYMyKib895r2SyCZv8cU+gXwq5I2Mu4ta9P3yahon4Iga/4qxb4JiC8kglJTg70ItQUFNiWMfCTu3nxBAmxa1cfankiT5N1qVRvcl7vtCHnHKjgnd+ZzmAmCYgCP6uhg2UT0Q5ME+daG07Rt2FRmJf9R1RhP/zABkf1E7e0EfDKZgY334yZZBpQvyP2ifu3cn0GClqb02tWDWGexzVuI/1sxxvJxvdyNOqT7UMjpxVDlQJMg5+JNgtemkRsNS0hgUnCw0ykSwG2l94EE7JFLMas+zUW6VODrlfv31+ihT5StCtOkZ/70aZ6Q7mtiPUK6QagOh3nU7ipPXKf0AI/IsgkArvv9AXAA8tcRxUdJBzplCtveoG+PL6iXK0oN7m6wYgJ5d8VX7eb68u3aYPxEfk2PuuSgwZfG2g6qWZxDE=

services:
- docker

before_install:
- pip install docker-compose
- docker --version

script:
- docker-compose -f docker-compose-build.yml build
- docker-compose -f docker-compose-build.yml up -d
- docker exec opac_opac_webapp_1 make test
- docker run -it --net host --pid host --cap-add audit_control -v /var/lib:/var/lib
  -v /var/run/docker.sock:/var/run/docker.sock -v /usr/lib/systemd:/usr/lib/systemd
  -v /etc:/etc --label docker_bench_security docker/docker-bench-security

after_success:

- docker login -u=$DOCKER_USER -p=$DOCKER_PASS

- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push"]; then
  docker build -t $TRAVIS_REPO_SLUG .;
  docker push $TRAVIS_REPO_SLUG;
  fi
