language: python
python:
  - "2.7"
script:
  - pip install -e git+https://github.com/scieloorg/opac_schema.git#egg=opac_schema
  - pip install -e git+https://github.com/jfunez/packtools.git#egg=html-generator-new
  - make test
