sudo: false
language: python
env:
  - OPAC_CONFIG="config.testing.templates"
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
  - pip install -r requirements.production.txt
script:
  - python manager.py test
services:
 - mongodb

