version: '2'

networks:
   opac-network:
    external: true

services:

    opac_mongo:
        image: mongo
        restart: always
        ports:
          - "27017:27017"
        hostname: opac_mongo
        networks:
            - opac-network

    opac_nginx:
        build: deploy/nginx/.
        restart: always
        ports:
            - "80:9000"
        networks:
            - opac-network
        hostname: opac_nginx

    opac_webapp_1:
        build: .
        restart: always
        working_dir: /app
        volumes:
            - ./data:/app/data
        links:
            - opac_nginx:opac_nginx
            - opac_mongo:opac_mongo
        ports:
            - "8000"
        networks:
            - opac-network
        environment:
            - OPAC_MONGODB_NAME=opac_mongo
            - OPAC_DATABASE_DIR=/app/data
