version: '2'

services:

    opac_mongo:
        image: mongo:latest
        restart: always
        user: nobody
        hostname: opac_mongo
        ports:
          - "27017:27017"

    opac_webapp:
        build: .
        user: nobody
        restart: always
        hostname: opac_webapp
        depends_on:
            - opac_mongo
        volumes:
            - ./data:/app/data
        links:
            - opac_mongo:opac_mongo
        ports:
            - "8000:8000"
        environment:
            - OPAC_DEBUG_MODE=True
            - OPAC_MONGODB_NAME=opac_mongo
            - OPAC_DATABASE_DIR=/app/data
            - OPAC_SECRET_KEY=s3kr3tk3y

    opac_nginx:
        image: scieloorg/opac_nginx:latest
        user: nobody
        restart: always
        depends_on:
            - opac_webapp
        links:
            - opac_webapp:opac-webapp
        ports:
            - "9000:9000"
        hostname: opac_nginx
